site_name: ROAR
site_description: Robot Autonomous Racing DeCal is a course dedicated to teaching students to gain a holistic view and hands-on(virtual) experiences about building a high-performance fully-autonomous 1/10 scale RC car from scratch.
site_url: https://roar-decal.github.io/Carla/
theme:
  name: material

nav:
  - Home: index.md
  - Setup: getting_started/quick_start.md
  - Project Overview:
      - Project Module TAD: project_overview/project_module_TADs.md
      - Code Layout: project_overview/code_layout.md
  - Code Documentations:
      - Bridges: code_documentations/bridges.md
      - ROAR Autonomous System:
          - Agents: code_documentations/roar_autonomous_system/agents.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: yes
            show_category_heading: yes
            show_if_no_docstring: yes
            show_source: true
            show_root_toc_entry: false
            show_object_full_path: false
